name: klar_{{name.snakeCase()}}
description: {{description.sentenceCase()}}
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  equatable: ^2.0.0

  klar_dependencies_base:
    path: ../klar_dependencies_base

dev_dependencies:
  # test_api 0.5.0 version has a breaking change
  test: 1.23.0

  klar_dart_lints:
    git:
      url: git@github.com:klar-mx/klar-dart-lints.git
      ref: 1.10.0
