name: talk_but_does_it_scale
description: "Can flutter applications scale to large teams?"
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.2"

dependencies:
  flutter:
    sdk: flutter

  presentation: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  shared_lints:
    path: ../shared_lints

  shared_theme:
    path: ../shared_theme

  shared_pages:
    path: ../shared_pages

  shared_ui:
    path: ../shared_ui

dependency_overrides:
  win32: ^5.0.0

flutter:
  uses-material-design: true
# Uncomment if the feature contains assets
#   assets:
#     - assets/
