// ignore_for_file: directives_ordering
/// This file is autogenerated and should not be committed to source control

import '../../test_driver/big_app_test.dart' as test_driver_big_app;
import '../../test_driver/code_reuse_test.dart' as test_driver_code_reuse;

void main(List<String> args) {
  test_driver_big_app.main(args);
  test_driver_code_reuse.main(args);
}
