// ignore_for_file: directives_ordering
/// This file is autogenerated and should not be committed to source control

import '../big_app_test.dart' as big_app;
import '../code_reuse_test.dart' as code_reuse;

void main(List<String> args) {
  big_app.main(args);
  code_reuse.main(args);
}
