name: shared_ui
description: UI components for the projects
version: 1.0.0
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  presentation: ^2.0.1

  shared_theme:
    path: ../shared_theme
    