// ignore_for_file: directives_ordering
/// This file is autogenerated on and should not be touched manually.
/// Please do not commit changes to this file.

import 'package:integration_test/integration_test.dart';

void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();
}
