name: feature_{{name.snakeCase()}}
description: "{{description.sentenceCase()}}"
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.2"

dependencies:
  flutter:
    sdk: flutter

  klar_dependencies_base:
    path: ../klar_dependencies_base

  klar_bloc_base:
    path: ../klar_bloc_base

  klar_shared_ui:
    path: ../klar_shared_ui

  klar_api_client:
    path: ../klar_api_client

dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: ^8.5.0
  mocktail: ^0.2.0

  klar_dart_lints:
    git:
      url: git@github.com:klar-mx/klar-dart-lints.git
      ref: 1.10.0

  klar_l10n_test_utils:
    path: ../klar_l10n/test_utils

  klar_test_bed:
    path: ../klar_test_bed

  klar_clock_test:
    path: ../klar_clock_test

  klar_bloc_test_bed:
    path: ../klar_bloc_test_bed

  klar_widget_test:
    path: ../klar_widget_test

dependency_overrides:
  win32: ^5.0.0

flutter:
  uses-material-design: true
# Uncomment if the feature contains assets
#   assets:
#     - assets/
