name: talk_refactoring
description: "Changing legacy code"
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.2"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.5
  presentation: ^2.2.0
  flutter_bloc: ^7.0.0
  google_fonts: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  shared_lints:
    path: ../shared_lints

  shared_theme:
    path: ../shared_theme

  shared_pages:
    path: ../shared_pages

  shared_ui:
    path: ../shared_ui



flutter:
  uses-material-design: true

  assets:
    - assets/
