
on: push
name: Analyze
jobs:
  build:
    name: Analyze
    runs-on: ubuntu-latest
    strategy:
      matrix:
        channel: [ "beta" ]

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: ${{ matrix.channel }}

      - name: Install melos
        run: dart pub global activate melos 2.7.1

      - name: Install dependencies
        run: melos run pub_get:all

      - name: Analyze
        run: melos run pr_check:all

