
on: push
name: Analyze
jobs:
  build:
    name: Analyze
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1.3.2
      with:
        channel: 'beta'
    - run: flutter doctor && flutter pub get
    - run: flutter analyze
    - run: flutter test

